name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm i -g pnpm
          pnpm run init
          pnpm run build:docs
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
        with: # 自定义环境变量
          BRANCH: gh-pages
          FOLDER: dist
          ACCESS_TOKEN: ${{ secrets.REACT_USE_SECRETS }}
          TARGET_FOLDER: react-use # 打包的文件将放到静态服务器 react-use 目录下

